apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: test
spec:
  type: LoadBalancer
  selector:
    app: test
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080